# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc857bbbaf9392d12a9cc022cdc7370c5244aea1ced3ed3347b8e28833dbb7e067dd0611772e2b7273e95fba8fd76a5f262f09a45f338b71efd4efbf48255ac8

test:
  secret_key_base: 9448bcf3228f7e1064e936cd912f7e01c48992b8495beae779f10fd078665327ad78aaa2d06dbc75c33c2db64840b7059834390dd799d7619fbd8bb492f32cd5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
